### ISSUE TITLE
Mesh simplification algorithm bug

### ISSUE THREAD

**Issue by MuhammedKalkan** [Nymria/TerrainGeneratorAndServer#1]
Simplification is not handling flat surfaces the way it has to
Also it sometimes produces cracks on terrain

**Comment by MuhammedKalkan** [comment]
Currently trying to solve this after bringing data merging up to a level.  Data merging is almost completed. 
I have other projects to deal with so this may take some time.

**Comment by kennywk** [comment]
Very interested in this work. Would be willing to contribute and do a java port if i can access the project.

**Comment by MuhammedKalkan** [comment]
Algorithm rewritten. Identical with the CesiumJS. Currently no bugs detected

**Comment by kennywk** [comment]
What method did you use for point selection? I.e determining the most significant points within a tile?
