### ISSUE TITLE
Identification json implementation

### ISSUE THREAD

**Issue by MuhammedKalkan** [Nymria/TerrainGeneratorAndServer#11]
Layers.json generation needs to be implemented

- [x] Tile Availability calculation 
- [x] Supported extensions for tileset
- [x] Bounds of the tileset
- [x] Attribution of the tileset

**Comment by Nymria** [comment]
Need to recheck tile availability calculation. I am gonna throw this way down in todo list

**Comment by MuhammedKalkan** [comment]
Completed
