### ISSUE TITLE
New data tile generation and merge

### ISSUE THREAD

**Issue by MuhammedKalkan** [Nymria/TerrainGeneratorAndServer#2]
Roadmap for new tile generation and merging

- [x] Tile data merge operations
- [x]  Watermask merge operations
- [x] Lighting calculation merge operations

**Comment by Nymria** [comment]
Workflow completed for this process.
Directory structure and intermediate processing done.

Region of Interest updating and last refactoring ongoing.

**Comment by Nymria** [comment]
Main algorithm completed. Result is  very good and shown below. 
![Result](https://dl.dropboxusercontent.com/s/vuwjf39lsez462l/5.png)

But there is a down side. Up level tiles will not match at the edges where high resolution data ends so there WILL be cliffs as shown below. In a very far future whole algorithm will change until then this is the way to go.
![KnownIssue](https://dl.dropboxusercontent.com/s/w5v1lk1gkujn53t/4.png)
