### ISSUE TITLE
Hope to get the quantizedMesh terrain

### ISSUE THREAD

**Issue by 543802360** [Nymria/TerrainGeneratorAndServer#24]
Greet job! I have established a terrain server with nodejs and mongoDB，but my terrain is heightmap，so can I use your tool to generate the QuantizedMesh terrain？If so，thanks a lot！

**Comment by MuhammedKalkan** [comment]
Hello,

Yes you will be able to use to generate your data into Quantized Mesh format when its ready.

You can track progress here or blog.

**Comment by 543802360** [comment]
Hello.
I have been following your progress through your github and blog.Maybe i can help with the storage and distribution of the terrain tiles.I have storaged my terrain tiles(HeightMap Format) into MongoDB, then established a terrain server to provider terrain services through REST api .So ,I can help on the Terrain Server

**Comment by MuhammedKalkan** [comment]
Hi there
What i meant was financially not tecnically. 
Thank you tho

**Comment by 543802360** [comment]
So embarrassed.I am a student now，good luck to you，you have done a very good job！
