### ISSUE TITLE
Emails are treated as spam, which is confusing

### ISSUE THREAD

**Issue by fnicollet** [Nymria/TerrainGeneratorAndServer#40]
Hello,

This is issue is more of a reminder for you than anything. Currently, the emails sent from TGS end up in the SPAM folder (at least on my gmail).
So emails with the password and the download links are kind of lost.

Not very user-friendly, if you want your software to be usable

Fabien

**Comment by MuhammedKalkan** [comment]
Will reevaluate in upcoming versions. Please ticket TTS for this
